# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fd0ecee18464e72119e9b24adaf7fda13f7140cc3c58287af44caf90a2adcdffcfe39a4033149e90e3f132c9054b96680e7e531a75147421022ed463d22def7

test:
  secret_key_base: e0de188721fe064e4b9778b30da427c0305eeb2a292efb32488938f044a9ed15b36db7816753205d03ca466c3c9d55c5253b158aea041334147c1e7c7e2c4208

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
